name: project-name

services:
  database:
    image: postgres:17
    container_name: project-name-database
    scale: 1
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d main -U username' ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - database:/data/postgres

volumes:
  database:
